### ISSUE TITLE
Bug with the Web Searchs plugin

### ISSUE THREAD

**Issue by Dominiquini** [jjw24/Wox#147]
### Are you submitting a bug report?

Yes

### Steps to reproduce

1. Bring the app to front
2. Input the text "twitter"
3. Click in the first and only item ("twitter - Activate Web Searchs plugin"
4. An error dialog appears!

* In the previous version, as soon as i finished typing the keyword, the edit box was already changed to indicate the search using the selected site.

### Wox Error Window text

Please open new issue in: https://github.com/Wox-launcher/Wox/issues/new
1. upload log file: C:\Users\Rafael Dominiquini\AppData\Roaming\Wox\Logs\1.43.20\2020-02-26.txt
2. copy below exception message

Wox version: 1.43.20
OS Version: Microsoft Windows NT 10.0.18363.0
IntPtr Length: 8
x64: True

Python Path: C:\Developing\Python\pythonw.exe
Everything SDK Path: C:\Users\Rafael Dominiquini\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 02/26/2020 00:42:34
Exception:
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Wox.Core.Plugin.QueryBuilder.Build(String text, Dictionary`2 nonGlobalPlugins) in C:\Workbench\Git\Wox\Wox.Core\Plugin\QueryBuilder.cs:line 27
   at Wox.ViewModel.MainViewModel.QueryResults() in C:\Workbench\Git\Wox\Wox\ViewModel\MainViewModel.cs:line 379
   at Wox.PublicAPIInstance.ChangeQuery(String query, Boolean requery) in C:\Workbench\Git\Wox\Wox\PublicAPIInstance.cs:line 44
   at Wox.Plugin.PluginIndicator.Main.<>c__DisplayClass1_1.<Query>b__4(ActionContext c) in C:\Workbench\Git\Wox\Plugins\Wox.Plugin.PluginIndicator\Main.cs:line 26
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_7(Object index) in C:\Workbench\Git\Wox\Wox\ViewModel\MainViewModel.cs:line 147
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

2020-02-26 00:37:00.5510|INFO|App.OnStartup|Begin Wox startup ----------------------------------------------------
2020-02-26 00:37:00.5710|INFO|App.OnStartup|Runtime info:
Wox version: 1.43.20
OS Version: Microsoft Windows NT 10.0.18363.0
IntPtr Length: 8
x64: True
2020-02-26 00:37:00.9390|INFO|ImageLoader.Initialize|Preload images cost <344ms>
2020-02-26 00:37:00.9440|INFO|ImageLoader.Initialize|Number of preload images is <33>, Images Number: 33, Unique Items 26
2020-02-26 00:37:00.9440|INFO|Wox.Infrastructure.Alphabet.Initialize|Preload pinyin cache <32ms>
2020-02-26 00:37:00.9440|INFO|Wox.Infrastructure.Alphabet.Initialize|Number of preload pinyin combination<0>
2020-02-26 00:37:01.5270|INFO|Wox.Plugin.Program.Main|Preload programs cost <8ms>
2020-02-26 00:37:01.5270|INFO|Wox.Plugin.Program.Main|Number of preload win32 programs <1034>
2020-02-26 00:37:01.5380|INFO|Wox.Plugin.Program.Main|Number of preload uwps <50>
2020-02-26 00:37:01.7910|INFO|PluginManager.InitializePlugins|Total init cost for <Hello World CSharp> is <2ms>
2020-02-26 00:37:01.7910|INFO|PluginManager.InitializePlugins|Total init cost for <Calculator> is <8ms>
2020-02-26 00:37:01.7910|INFO|PluginManager.InitializePlugins|Total init cost for <Folder> is <5ms>
2020-02-26 00:37:01.7910|INFO|PluginManager.InitializePlugins|Total init cost for <Everything> is <7ms>
2020-02-26 00:37:01.8020|INFO|PluginManager.InitializePlugins|Total init cost for <Shell> is <7ms>
2020-02-26 00:37:01.7910|INFO|PluginManager.InitializePlugins|Total init cost for <Colors> is <1ms>
2020-02-26 00:37:01.7910|INFO|PluginManager.InitializePlugins|Total init cost for <Plugin Indicator> is <1ms>
2020-02-26 00:37:01.8020|INFO|PluginManager.InitializePlugins|Total init cost for <System Commands> is <2ms>
2020-02-26 00:37:01.7910|INFO|PluginManager.InitializePlugins|Total init cost for <Browser Bookmarks> is <503ms>
2020-02-26 00:37:01.7910|INFO|PluginManager.InitializePlugins|Total init cost for <Wox Plugin Management> is <1ms>
2020-02-26 00:37:01.8020|INFO|PluginManager.InitializePlugins|Total init cost for <Program> is <43ms>
2020-02-26 00:37:01.8210|INFO|PluginManager.InitializePlugins|Total init cost for <URL> is <3ms>
2020-02-26 00:37:01.8210|INFO|PluginManager.InitializePlugins|Total init cost for <Web Searches> is <11ms>
2020-02-26 00:37:01.8330|INFO|PluginManager.InitializePlugins|Total init cost for <Hello World Python> is <0ms>
2020-02-26 00:37:01.8700|INFO|PluginManager.InitializePlugins|Total init cost for <Control Panel> is <82ms>
2020-02-26 00:37:01.8810|INFO|App.OnStartup|Dependencies Info:
Python Path: C:\Developing\Python\pythonw.exe
Everything SDK Path: C:\Users\Rafael Dominiquini\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
2020-02-26 00:37:01.9020|INFO|App.OnStartup|End Wox startup ----------------------------------------------------  
2020-02-26 00:37:01.9020|INFO|App.OnStartup|Startup cost <1474ms>
2020-02-26 00:37:07.3522|FATAL|UnHandledException|
## Exception

```
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   Source: mscorlib
   TargetAssembly: mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
   TargetModule: CommonLanguageRuntimeLibrary
   TargetSite: System.String Substring(Int32, Int32)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Wox.Core.Plugin.QueryBuilder.Build(String text, Dictionary`2 nonGlobalPlugins) in C:\Workbench\Git\Wox\Wox.Core\Plugin\QueryBuilder.cs:line 27
   at Wox.ViewModel.MainViewModel.QueryResults() in C:\Workbench\Git\Wox\Wox\ViewModel\MainViewModel.cs:line 379
   at Wox.PublicAPIInstance.ChangeQuery(String query, Boolean requery) in C:\Workbench\Git\Wox\Wox\PublicAPIInstance.cs:line 44
   at Wox.Plugin.PluginIndicator.Main.<>c__DisplayClass1_1.<Query>b__4(ActionContext c) in C:\Workbench\Git\Wox\Plugins\Wox.Plugin.PluginIndicator\Main.cs:line 26
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_7(Object index) in C:\Workbench\Git\Wox\Wox\ViewModel\MainViewModel.cs:line 147
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

## Environment
* Command Line: "C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Wox.exe" 
* Timestamp: 02/26/2020 00:37:07
* Wox version: 1.43.20
* OS Version: Microsoft Windows NT 10.0.18363.0
* IntPtr Length: 8
* x64: True
* Python Path: C:\Developing\Python\pythonw.exe
* Everything SDK Path: C:\Users\Rafael Dominiquini\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
* CLR Version: 4.0.30319.42000
* Installed .NET Framework: 
   * v2.0.50727 2.0.50727.4927 SP2
   * v3.0 3.0.30729.4926 SP2
   * v3.5 3.5.30729.4926 SP1
   * v4 Client 4.8.03752
   * v4 Full 4.8.03752
   * v4.0 Client 4.0.0.0

## Assemblies - Wox.exe

* Wox, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Wox.exe)
* Wox.Core, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Wox.Core.dll)
* Wox.Infrastructure, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Wox.Infrastructure.dll)
* Pinyin4Net, Version=2016.4.24.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Pinyin4Net.dll)
* Wox.Plugin, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Wox.Plugin.dll)
* NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\NLog.dll)
* Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Newtonsoft.Json.dll)
* HelloWorldCSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\HelloWorldCSharp\HelloWorldCSharp.dll)
* Wox.Plugin.BrowserBookmark, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.BrowserBookmark\Wox.Plugin.browserBookmark.dll)
* System.Data.SQLite, Version=1.0.111.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139 (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.BrowserBookmark\System.Data.SQLite.dll)
* UnidecodeSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.BrowserBookmark\UnidecodeSharp.dll)
* Wox.Plugin.Caculator, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.Caculator\Wox.Plugin.Caculator.dll)
* Mages.Core, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.Caculator\Mages.Core.dll)
* Wox.Plugin.Color, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.Color\Wox.Plugin.Color.dll)
* Wox.Plugin.ControlPanel, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.ControlPanel\Wox.Plugin.ControlPanel.dll)
* Wox.Plugin.Everything, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.Everything\Wox.Plugin.Everything.dll)
* Wox.Plugin.Folder, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.Folder\Wox.Plugin.Folder.dll)
* Wox.Plugin.PluginIndicator, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.PluginIndicator\Wox.Plugin.PluginIndicator.dll)
* Wox.Plugin.PluginManagement, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.PluginManagement\Wox.Plugin.PluginManagement.dll)
* Wox.Plugin.Program, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.Program\Wox.Plugin.Program.dll)
* Wox.Plugin.Shell, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.Shell\Wox.Plugin.Shell.dll)
* WindowsInput, Version=1.0.4.0, Culture=neutral, PublicKeyToken=9b287f7dc5073cad (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\WindowsInput.dll)
* Wox.Plugin.Sys, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.Sys\Wox.Plugin.Sys.dll)
* Wox.Plugin.Url, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.Url\Wox.Plugin.Url.dll)
* Wox.Plugin.WebSearch, Version=1.43.20.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Plugins\Wox.Plugin.WebSearch\Wox.Plugin.WebSearch.dll)
* NHotkey, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\NHotkey.dll)
* NHotkey.Wpf, Version=1.2.1.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\NHotkey.Wpf.dll)
* Squirrel, Version=1.5.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Squirrel.dll)
* Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null (C:\Users\Rafael Dominiquini\AppData\Local\Wox\app-1.43.20\Splat.dll)
* mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscorlib.dll)
* PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll)
* WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll)
* System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll)
* System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll)
* PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll)
* System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll)
* System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Remoting\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Remoting.dll)
* System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll)
* System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll)
* System.ServiceModel, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll)
* System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll)
* System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll)
* System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll)
* System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll)
* System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll)
* System.Transactions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll)
* System.EnterpriseServices, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a (C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll)
* PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll)
* System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll)
* PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemData\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemData.dll)
* UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll)
* UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll)
* PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll)
* PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 (C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll)

### Screenshots (optional)

(drop your screenshot here)

**Comment by Dominiquini** [comment]
I tested the new version and it seems to be working fine!
I think you can close the bug!

Thanks
