### ISSUE TITLE
Wox crashes when searching for Putty connection

### ISSUE THREAD

**Issue by katchy3132** [jjw24/Wox#150]
### Are you submitting a bug report?

yes

### Steps to reproduce

1. using the Putty plugin searched for a saved putty connection. 

2. hit return and then the crash occurs 
3.This works with the regular Wox 1.3.578

### Wox Error Window text

Wox version: 1.43.20
OS Version: Microsoft Windows NT 10.0.18363.0
IntPtr Length: 8
x64: True

Python Path: C:\Conda\pythonw.exe
Everything SDK Path: C:\Users\Yo\AppData\Roaming\Wox\Settings\Plugins\Wox.Plugin.Everything\EverythingSDK\x64\Everything.dll
Date: 02/26/2020 16:25:29
Exception:
System.MissingMethodException: Method not found: 'Void Wox.Plugin.IPublicAPI.ShowMsg(System.String, System.String, System.String)'.
   at Wox.Plugin.Putty.PuttyPlugin.<>c__DisplayClass2.<MakeResult>b__1(ActionContext e)
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_7(Object index) in C:\Workbench\Git\Wox\Wox\ViewModel\MainViewModel.cs:line 147
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Detailed logs

[2020-02-26.txt](https://github.com/jjw24/Wox/files/4256236/2020-02-26.txt)

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/3707138/75354578-dc812f00-58b5-11ea-9657-58d9d9aeec32.png)

**Comment by feeas** [comment]
Same issue in https://github.com/harrynull/WoxDictionary, when you click on a word to see the detail ,wox crashes.

System.MissingMethodException: Method not found: 'Void Wox.Plugin.IPublicAPI.ShowMsg(System.String, System.String, System.String)'.
   Source: Dictionary
   TargetAssembly: Dictionary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
   TargetModule: Dictionary.dll
   TargetSite: Boolean <MakeResultItem>g__CopyIfNeeded|0(Wox.Plugin.ActionContext)
   at Dictionary.Main.<>c__DisplayClass10_0.<MakeResultItem>g__CopyIfNeeded|0(ActionContext e)
   at Dictionary.Main.<>c__DisplayClass10_0.<MakeResultItem>b__1(ActionContext e)
   at Wox.ViewModel.MainViewModel.<InitializeKeyCommands>b__16_7(Object index) in C:\Workbench\Git\Wox\Wox\ViewModel\MainViewModel.cs:line 150
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jjw24** [comment]
Haven't had a chance to fix this yet. Will do soon.

**Comment by jjw24** [comment]
Hi @katchy3132 @gundamhyl , issue has been fixed. Please update your Wox to the latest. Thanks @theClueless
